stages:
  - build
  - test
  - migrate
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  SPRING_PROFILES_ACTIVE: "prod"
  LIQUIBASE_CHANGELOG: "db/changelog/db.changelog-master.xml"

cache:
  paths:
    - .m2/repository
    - target/

build:
  stage: build
  image: maven:3.8.5-openjdk-17
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 hour

test:
  stage: test
  image: maven:3.8.5-openjdk-17
  services:
    - name: mysql:8.0
      alias: mysql
      variables:
        MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
        MYSQL_DATABASE: $DB_NAME
  script:
    - mvn test -Dspring.datasource.url=jdbc:mysql://mysql:3306/$DB_NAME
      -Dspring.datasource.username=root
      -Dspring.datasource.password=$DB_ROOT_PASSWORD

migrate:
  stage: migrate
  image: liquibase/liquibase:4.20.0
  variables:
    LIQUIBASE_URL: jdbc:mysql://$DB_HOST:3306/$DB_NAME?useSSL=false
    LIQUIBASE_USERNAME: $DB_USER
    LIQUIBASE_PASSWORD: $DB_PASSWORD
    LIQUIBASE_CHANGELOG: $LIQUIBASE_CHANGELOG
  script:
    - liquibase update
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual

deploy:
  stage: deploy
  image: openjdk:17
  environment:
    name: production
    url: https://votre-application.com
  script:
    - java -jar target/*.jar --spring.profiles.active=$SPRING_PROFILES_ACTIVE
  only:
    - main