name: CI Liquibase Pipeline

on:
  push:
    branches:
      - master  # ou ta branche principale

jobs:
  liquibase-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build and run Liquibase update
        run: mvn clean compile liquibase:update
