name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: springboot-artifacts
          path: springboot-swagger-crud

      - name: Verify Download
        run: ls -la springboot-swagger-crud/target/

      - name: Build and Push Docker Image
        working-directory: springboot-swagger-crud
        run: |
          docker build -t oumaimamaghraoui27/springboot-app:${{ github.sha }} .
          docker push oumaimamaghraoui27/springboot-app:${{ github.sha }}

      - name: Apply Migrations
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.PROD_DB_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.PROD_DB_USER }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
        run: |
          docker run --rm \
            -e SPRING_PROFILES_ACTIVE=prod \
            -e SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL \
            -e SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME \
            -e SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD \
            -e SPRING_LIQUIBASE_ENABLED=true \
            oumaimamaghraoui27/springboot-app:${{ github.sha }} \
            java -jar target/*.jar \
            --spring.main.web-application-type=none