name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Download CI Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t oumaimamaghraoui27/springboot-app:${{ github.sha }} .
          docker push oumaimamaghraoui27/springboot-app:${{ github.sha }}

      - name: Apply Production Migrations
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.PROD_DB_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.PROD_DB_USER }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
        run: |
          docker run --rm \
            -e SPRING_PROFILES_ACTIVE=prod \
            -e SPRING_DATASOURCE_URL=${{ env.SPRING_DATASOURCE_URL }} \
            -e SPRING_DATASOURCE_USERNAME=${{ env.SPRING_DATASOURCE_USERNAME }} \
            -e SPRING_DATASOURCE_PASSWORD=${{ env.SPRING_DATASOURCE_PASSWORD }} \
            -e SPRING_LIQUIBASE_ENABLED=true \
            oumaimamaghraoui27/springboot-app:${{ github.sha }} \
            java -jar *.jar \
            --spring.main.web-application-type=none

      - name: Deploy Application
        run: |
          echo "Deploy to Kubernetes/ECS here (example)"
          # kubectl apply -f k8s.yaml