name: CI Pipeline

on: [push]

env:
  SPRING_PROFILES_ACTIVE: ci
  SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/oumaima?useSSL=false
  SPRING_LIQUIBASE_ENABLED: true

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword123
          MYSQL_DATABASE: oumaima
          MYSQL_USER: ${{ secrets.DB_USER }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -uroot -prootpassword123"
          --health-interval=5s
          --health-timeout=10s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4
      - name: Navigate to project folder
        run: |
          cd springboot-swagger-crud || { echo "Error: Project folder not found"; exit 1; }
          echo "PROJECT_DIR=$(pwd)" >> $GITHUB_ENV
          JAR_FILE=$(ls target/ | grep -E '^springboot-swagger-crud.*\.jar$')
          if [ -z "$JAR_FILE" ]; then
            echo "Error: No JAR file found in target/"
            exit 1
          fi
          echo "JAR_FILE=target/$JAR_FILE" >> $GITHUB_ENV
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait for MySQL
        run: |
          for i in {1..10}; do
            if mysqladmin ping -h127.0.0.1 -uroot -prootpassword123 --silent; then
              exit 0
            fi
            sleep 2
          done
          exit 1

      - name: Build and Test
        run: ./mvnw clean verify

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            target/*.jar
            Dockerfile
            src/main/resources/db/changelog/**
          retention-days: 1  # Clean up after 1 day