name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword123
          MYSQL_DATABASE: oumaima
          # Remove MYSQL_USER and MYSQL_PASSWORD for root
          # Keep only root password configuration
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -uroot -prootpassword123"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait for MySQL
        run: |
          for i in {1..10}; do
            if mysqladmin ping -h127.0.0.1 -uroot -prootpassword123 --silent; then
              break
            fi
            sleep 5
          done

      - name: Build with Maven
        run: |
          ./mvnw -B clean install
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/oumaima?useSSL=false&allowPublicKeyRetrieval=true
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: rootpassword123
          SPRING_JPA_HIBERNATE_DDL_AUTO: update

      - name: Verify MySQL connection
        run: |
          mysql --host=127.0.0.1 --user=root --password=rootpassword123 -e "SHOW DATABASES;"