name: CI/CD Pipeline

on: [push]

env:
  DB_NAME: oumaima
  DB_HOST: 127.0.0.1  # Use 127.0.0.1 instead of localhost
  DB_USER: appuser
  DB_PASSWORD: apppassword

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword123
          MYSQL_DATABASE: ${{ env.DB_NAME }}
          MYSQL_USER: ${{ env.DB_USER }}
          MYSQL_PASSWORD: ${{ env.DB_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configure MySQL permissions
        run: |
          for i in {1..10}; do
            if mysqladmin ping -h127.0.0.1 -uroot -prootpassword123 --silent; then
              mysql -h127.0.0.1 -uroot -prootpassword123 -e "
                CREATE DATABASE IF NOT EXISTS ${{ env.DB_NAME }};
                GRANT ALL PRIVILEGES ON ${{ env.DB_NAME }}.* TO '${{ env.DB_USER }}'@'%';
                FLUSH PRIVILEGES;
              "
              break
            fi
            sleep 3
          done

      - name: Run Liquibase Migrations
        run: |
          ./mvnw liquibase:update \
            -Dliquibase.url=jdbc:mysql://${{ env.DB_HOST }}:3306/${{ env.DB_NAME }}?useSSL=false \
            -Dliquibase.username=${{ env.DB_USER }} \
            -Dliquibase.password=${{ env.DB_PASSWORD }} \
            -Dliquibase.changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml \
            -Dliquibase.driver=com.mysql.cj.jdbc.Driver

      - name: Build and test
        run: |
          ./mvnw clean install -Dspring-boot.run.profiles=pipeline
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://${{ env.DB_HOST }}:3306/${{ env.DB_NAME }}?useSSL=false
          SPRING_DATASOURCE_USERNAME: ${{ env.DB_USER }}
          SPRING_DATASOURCE_PASSWORD: ${{ env.DB_PASSWORD }}