name: CI/CD Pipeline

on: [push]

env:
  DB_NAME: oumaima
  DB_HOST: 127.0.0.1
  DB_USER: appuser
  DB_PASSWORD: apppassword
  SPRING_PROFILES_ACTIVE: pipeline
  SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/oumaima?useSSL=false&allowPublicKeyRetrieval=true
  SPRING_DATASOURCE_USERNAME: appuser
  SPRING_DATASOURCE_PASSWORD: apppassword

jobs:
  build-and-test:
    name: Build, Test & Migrate DB
    runs-on: ubuntu-latest
    timeout-minutes: 20

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword123
          MYSQL_DATABASE: oumaima
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -uroot -prootpassword123"
          --health-interval=5s
          --health-timeout=10s
          --health-retries=10

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Navigate to project folder and define PROJECT_DIR
        run: |
          cd springboot-swagger-crud
          echo "PROJECT_DIR=$(pwd)" >> $GITHUB_ENV
          ls -la

      - name: Set up JDK 17 with Temurin
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configure MySQL user and permissions
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h127.0.0.1 -uroot -prootpassword123 --silent; then
              mysql -h127.0.0.1 -uroot -prootpassword123 -e "
                CREATE DATABASE IF NOT EXISTS ${DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
                DROP USER IF EXISTS '${DB_USER}'@'%';
                CREATE USER '${DB_USER}'@'%' IDENTIFIED BY '${DB_PASSWORD}';
                GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'%';
                GRANT PROCESS, RELOAD, REPLICATION CLIENT ON *.* TO '${DB_USER}'@'%';
                GRANT CREATE TEMPORARY TABLES ON ${DB_NAME}.* TO '${DB_USER}'@'%';
                GRANT LOCK TABLES ON ${DB_NAME}.* TO '${DB_USER}'@'%';
                FLUSH PRIVILEGES;
              "
              break
            fi
            echo "Waiting for MySQL to be ready (attempt $i)..."
            sleep 3
          done

      - name: Verify MySQL DB connection and visibility
        run: |
          mysql -h127.0.0.1 -u${DB_USER} -p${DB_PASSWORD} -e "SHOW DATABASES; USE ${DB_NAME}; SHOW TABLES;"

      - name: Compile project (copy resources)
        working-directory: ${{ env.PROJECT_DIR }}
        run: ./mvnw clean compile

      - name: Debug system and project environment
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          echo "=== Environment Debug ==="
          java -version
          ./mvnw -v || mvn -v
          ls -la
          ls -la src/main/resources/db/changelog/
          mysql -h127.0.0.1 -u${DB_USER} -p${DB_PASSWORD} -e "SELECT 1" ${DB_NAME}

      - name: Check mvnw file existence
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          ls -la
          if [ ! -f ./mvnw ]; then
            echo "❌ mvnw not found!"
            exit 1
          fi

      - name: Run Liquibase database migrations
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          cat << 'EOF' > run_liquibase.sh
#!/bin/bash
          set +e
          
          ./mvnw liquibase:update \
          -Dliquibase.url="jdbc:mysql://127.0.0.1:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true" \
          -Dliquibase.username="${DB_USER}" \
          -Dliquibase.password="${DB_PASSWORD}" \
          -Dliquibase.driver=com.mysql.cj.jdbc.Driver \
          -Dliquibase.changeLogFile=db/changelog/db.changelog-master.xml \
          -Dliquibase.searchPath=src/main/resources
  
          STATUS=$?
  
          if [ $STATUS -eq 0 ]; then
          echo "::notice::Liquibase migration succeeded"
          exit 0
          else
          echo "::error::Liquibase migration failed"
          exit $STATUS
          fi
          EOF
          chmod +x run_liquibase.sh
          ./run_liquibase.sh

      - name: Build and run tests with Maven
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          ./mvnw clean install \
            -Dspring-boot.run.profiles=pipeline \
            -Dspring.datasource.url=${SPRING_DATASOURCE_URL} \
            -Dspring.datasource.username=${SPRING_DATASOURCE_USERNAME} \
            -Dspring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

      - name: Verify Liquibase changelog execution
        run: |
          mysql -h127.0.0.1 -u${DB_USER} -p${DB_PASSWORD} -e "
            USE ${DB_NAME};
            SHOW TABLES;
            SELECT 
              id, 
              author, 
              filename, 
              dateexecuted,
              MD5SUM,
              CASE WHEN EXECTYPE = 'EXECUTED' THEN 'Success' ELSE 'Failed' END AS status
            FROM DATABASECHANGELOG
            ORDER BY dateexecuted DESC;
          "
