name: Java CI with Maven and Liquibase

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install
        working-directory: springboot-swagger-crud

      - name: Run Liquibase update
        run: mvn liquibase:update
        working-directory: springboot-swagger-crud
