name: CI/CD Pipeline

on: [push]

jobs:
  build-and-migrate:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword123
          MYSQL_DATABASE: oumaima
          MYSQL_USER: appuser
          MYSQL_PASSWORD: apppassword
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -uroot -prootpassword123"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Find project directory
        id: find_project
        run: |
          # Solution universelle qui trouve le dossier contenant pom.xml
          PROJECT_DIR=$(find . -name pom.xml -printf '%h\n' | head -1)
          echo "PROJECT_DIR=${PROJECT_DIR}" >> $GITHUB_OUTPUT
          echo "Found project at: ${PROJECT_DIR}"
          ls -la "${PROJECT_DIR}"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test
        working-directory: ${{ steps.find_project.outputs.PROJECT_DIR }}
        run: |
          chmod +x mvnw
          ./mvnw -B clean install -Dspring-boot.run.profiles=pipeline
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/oumaima?useSSL=false
          SPRING_DATASOURCE_USERNAME: appuser
          SPRING_DATASOURCE_PASSWORD: apppassword

      - name: Run Liquibase migrations
        working-directory: ${{ steps.find_project.outputs.PROJECT_DIR }}
        run: |
          ./mvnw liquibase:update \
            -Dliquibase.url=jdbc:mysql://127.0.0.1:3306/oumaima \
            -Dliquibase.username=appuser \
            -Dliquibase.password=apppassword \
            -Dliquibase.changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml

      - name: Verify database
        run: |
          mysql --host=127.0.0.1 --user=appuser --password=apppassword -e "
            USE oumaima;
            SELECT * FROM DATABASECHANGELOG;
            SHOW TABLES;
          "