name: CI/CD Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword123
          MYSQL_DATABASE: oumaima
          MYSQL_USER: appuser
          MYSQL_PASSWORD: apppassword
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -uroot -prootpassword123"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait for MySQL
        run: |
          for i in {1..10}; do
            if mysqladmin ping -h127.0.0.1 -uroot -prootpassword123 --silent; then
              break
            fi
            sleep 5
          done
          sleep 3  # Additional buffer for user creation

      - name: Build with Maven (Pipeline Profile)
        run: |
          ./mvnw -B clean install -Dspring-boot.run.profiles=pipeline
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/oumaima?useSSL=false&allowPublicKeyRetrieval=true
          SPRING_DATASOURCE_USERNAME: appuser
          SPRING_DATASOURCE_PASSWORD: apppassword

      - name: Verify Database Access
        run: |
          # Verify root can access
          mysql --host=127.0.0.1 --user=root --password=rootpassword123 -e "SHOW DATABASES;"
          
          # Verify app user can access with limited privileges
          mysql --host=127.0.0.1 --user=appuser --password=apppassword -e "SHOW GRANTS FOR appuser;"
          
          # Verify schema was created properly
          mysql --host=127.0.0.1 --user=appuser --password=apppassword -e "USE oumaima; SHOW TABLES;"