name: CI/CD Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword123
          MYSQL_DATABASE: oumaima
          MYSQL_USER: appuser
          MYSQL_PASSWORD: apppassword
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -uroot -prootpassword123"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..10}; do
            if mysqladmin ping -h127.0.0.1 -uroot -prootpassword123 --silent; then
              echo "MySQL is ready!"
              break
            fi
            echo "Waiting for MySQL... Attempt $i"
            sleep 5
          done

      - name: Build with Maven
        run: ./mvnw -B clean package -DskipTests
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/oumaima?useSSL=false&allowPublicKeyRetrieval=true
          SPRING_DATASOURCE_USERNAME: appuser
          SPRING_DATASOURCE_PASSWORD: apppassword

      - name: Run Tests with Database
        run: ./mvnw test
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/oumaima?useSSL=false
          SPRING_DATASOURCE_USERNAME: appuser
          SPRING_DATASOURCE_PASSWORD: apppassword
          SPRING_JPA_HIBERNATE_DDL_AUTO: none  # Désactive la génération automatique du schéma

      - name: Run Liquibase migrations
        run: |
          ./mvnw liquibase:update \
            -Dliquibase.url=jdbc:mysql://127.0.0.1:3306/oumaima \
            -Dliquibase.username=appuser \
            -Dliquibase.password=apppassword \
            -Dliquibase.changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml

      - name: Verify Database
        run: |
          mysql --host=127.0.0.1 --user=appuser --password=apppassword -e "
            USE oumaima;
            SHOW TABLES;
            SELECT * FROM DATABASECHANGELOG;
          "