name: CI/CD Pipeline

on: [push]

env:
  DB_NAME: oumaima
  DB_HOST: 127.0.0.1
  DB_USER: appuser
  DB_PASSWORD: apppassword
  SPRING_PROFILES_ACTIVE: pipeline

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword123
          MYSQL_DATABASE: oumaima  # Hardcoded to match env.DB_NAME
          MYSQL_USER: appuser     # Hardcoded to match env.DB_USER
          MYSQL_PASSWORD: apppassword  # Hardcoded to match env.DB_PASSWORD
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -uappuser -papppassword"
          --health-interval=5s

    steps:
      - uses: actions/checkout@v4

      - name: Navigate to project
        run: |
          cd springboot-swagger-crud
          echo "PROJECT_DIR=$(pwd)" >> $GITHUB_ENV
          ls -la

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configure MySQL permissions
        run: |
          for i in {1..15}; do
            if mysqladmin ping -h127.0.0.1 -uroot -prootpassword123 --silent; then
              mysql -h127.0.0.1 -uroot -prootpassword123 -e "
                CREATE DATABASE IF NOT EXISTS ${{ env.DB_NAME }};
                CREATE USER IF NOT EXISTS '${{ env.DB_USER }}'@'%' IDENTIFIED WITH mysql_native_password BY '${{ env.DB_PASSWORD }}';
                GRANT ALL ON ${{ env.DB_NAME }}.* TO '${{ env.DB_USER }}'@'%';
                FLUSH PRIVILEGES;
              "
              break
            fi
            sleep 2
          done

      - name: Verify DB connection
        run: |
          mysql -h127.0.0.1 -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} -e "SHOW DATABASES;"

      - name: Run Liquibase migrations
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          ./mvnw liquibase:update \
            -Dliquibase.url=jdbc:mysql://${{ env.DB_HOST }}:3306/${{ env.DB_NAME }}?useSSL=false \
            -Dliquibase.username=${{ env.DB_USER }} \
            -Dliquibase.password=${{ env.DB_PASSWORD }} \
            -Dliquibase.driver=com.mysql.cj.jdbc.Driver \
            -Dliquibase.changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml

      - name: Build and test
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          ./mvnw clean install \
            -Dspring-boot.run.profiles=pipeline \
            -Dspring.datasource.url=jdbc:mysql://${{ env.DB_HOST }}:3306/${{ env.DB_NAME }}?useSSL=false \
            -Dspring.datasource.username=${{ env.DB_USER }} \
            -Dspring.datasource.password=${{ env.DB_PASSWORD }}

      - name: Verify migrations
        run: |
          mysql -h127.0.0.1 -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} -e "
            USE ${{ env.DB_NAME }};
            SHOW TABLES;
            SELECT id, author, filename, dateexecuted FROM DATABASECHANGELOG;
          "